<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="epidimensionsrefgroup" nsURI="http://www.example.org/epidimensionsrefgroup"
    nsPrefix="epidimensionsrefgroup">
  <eClassifiers xsi:type="ecore:EClass" name="Epidemic" eSuperTypes="../../epidimensionsbase/model/epidimensionsbase.ecore#//Epidemic">
    <eStructuralFeatures xsi:type="ecore:EReference" name="idimension" upperBound="-1"
        eType="#//IDimension" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IDimension" abstract="true" interface="true"
      eSuperTypes="../../epidimensionsbase/model/epidimensionsbase.ecore#//Dimension ../../epidimensionsbase/model/epidimensionsbase.ecore#//Compartment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dimension" eSuperTypes="#//IDimension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="flow_2" upperBound="-1"
        eType="#//Flow" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="idimension" upperBound="-1"
        eType="#//IDimension" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DimensionRef" eSuperTypes="#//IDimension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="idimension" eType="#//IDimension"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Compartment" eSuperTypes="../../epidimensionsbase/model/epidimensionsbase.ecore#//Compartment #//IDimension"/>
  <eClassifiers xsi:type="ecore:EClass" name="Flow" abstract="true" eSuperTypes="../../epidimensionsbase/model/epidimensionsbase.ecore#//Flow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from_dimension" eType="#//IDimension"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to_dimension" eType="#//IDimension"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rate" eSuperTypes="#//Flow ../../epidimensionsbase/model/epidimensionsbase.ecore#//Rate"/>
  <eClassifiers xsi:type="ecore:EClass" name="Batch" eSuperTypes="#//Flow ../../epidimensionsbase/model/epidimensionsbase.ecore#//Batch"/>
  <eClassifiers xsi:type="ecore:EClass" name="Contact" eSuperTypes="#//Flow ../../epidimensionsbase/model/epidimensionsbase.ecore#//Contact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contact_dimension" eType="#//IDimension"/>
  </eClassifiers>
</ecore:EPackage>
