<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="epimodelgroup" nsURI="http://www.example.org/epimodelgroup"
    nsPrefix="epimodelgroup">
  <eClassifiers xsi:type="ecore:EClass" name="Epidemic">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimension" upperBound="-1"
        eType="#//IDimension" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IDimension" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dimension" eSuperTypes="#//IDimension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compartment" upperBound="-1"
        eType="#//IDimension" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flow" upperBound="-1" eType="#//MetaFlow"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetaCompartment" eSuperTypes="#//IDimension"/>
  <eClassifiers xsi:type="ecore:EClass" name="MetaFlow" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//IDimension"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//IDimension"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DimensionRef" eSuperTypes="#//IDimension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//IDimension"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetaContact" eSuperTypes="#//MetaFlow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contact" eType="#//IDimension"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetaRate" eSuperTypes="#//MetaFlow"/>
  <eClassifiers xsi:type="ecore:EClass" name="MetaBatch" eSuperTypes="#//MetaFlow"/>
</ecore:EPackage>
