<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="compartmentLink" nsURI="http://www.example.org/compartmentLink"
    nsPrefix="compartmentLink">
  <eClassifiers xsi:type="ecore:EClass" name="CompartmentLink" eSuperTypes="../../epimodel/model/epimodel.ecore#//Compartment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compartment" eType="ecore:EClass ../../epimodel/model/epimodel.ecore#//CompartmentWrapper"/>
  </eClassifiers>
</ecore:EPackage>
