<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="batchRateContactFlows" nsURI="http://www.example.org/batchRateContactFlows"
    nsPrefix="batchRateContactFlows">
  <eClassifiers xsi:type="ecore:EClass" name="Batch" eSuperTypes="#//FromToFlow"/>
  <eClassifiers xsi:type="ecore:EClass" name="Rate" eSuperTypes="#//FromToFlow"/>
  <eClassifiers xsi:type="ecore:EClass" name="Contact" eSuperTypes="#//FromToFlow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contact" eType="ecore:EClass ../../epimodel/model/epimodel.ecore#//Compartment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FromToFlow" eSuperTypes="../../epimodel/model/epimodel.ecore#//Flow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="ecore:EClass ../../epimodel/model/epimodel.ecore#//Compartment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="ecore:EClass ../../epimodel/model/epimodel.ecore#//Compartment"/>
  </eClassifiers>
</ecore:EPackage>
