/**
 *
 * $Id$
 */
package seirmodel.validation;

import org.eclipse.emf.common.util.EList;
import seirmodel.Flow;


/**
 * A sample validator interface for {@link seirmodel.Compartment}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CompartmentValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validatePopulation(int value);

	boolean validateOutgoingFlows(EList<Flow> value);
}
