/**
 *
 * $Id$
 */
package seirmodel.validation;

import seirmodel.Compartment;

/**
 * A sample validator interface for {@link seirmodel.Flow}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FlowValidator {
	boolean validate();

	boolean validateRate(double value);
	boolean validateDescription(String value);
	boolean validateTarget(Compartment value);
}
