/**
 *
 * $Id$
 */
package seirmodel.validation;

import org.eclipse.emf.common.util.EList;
import seirmodel.Compartment;

/**
 * A sample validator interface for {@link seirmodel.SEIRModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SEIRModelValidator {
	boolean validate();

	boolean validateCompartments(EList<Compartment> value);

	boolean validateCompartments(Compartment value);
}
