<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="compartmentGroup" nsURI="http://www.example.org/compartmentGroup"
    nsPrefix="compartmentGroup">
  <eClassifiers xsi:type="ecore:EClass" name="Group" eSuperTypes="../../epimodel/model/epimodel.ecore#//Compartment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compartment" upperBound="-1"
        eType="ecore:EClass ../../epimodel/model/epimodel.ecore#//CompartmentWrapper"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flow" upperBound="-1" eType="ecore:EClass ../../epimodel/model/epimodel.ecore#//FlowWrapper"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groupSinks" eType="#//GroupSinks"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groupSources" eType="#//GroupSources"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GroupSources" eSuperTypes="#//End"/>
  <eClassifiers xsi:type="ecore:EClass" name="GroupSinks" eSuperTypes="#//End"/>
  <eClassifiers xsi:type="ecore:EClass" name="End">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" upperBound="-1" eType="#//Link"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compartment" eType="ecore:EClass ../../epimodel/model/epimodel.ecore#//Compartment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GroupEpidemic" eSuperTypes="../../epimodel/model/epimodel.ecore#//Epidemic">
    <eStructuralFeatures xsi:type="ecore:EReference" name="groupSinks" eType="#//GroupSinks"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groupSources" eType="#//GroupSources"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flow" upperBound="-1" eType="ecore:EClass ../../epimodel/model/epimodel.ecore#//FlowWrapper"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compartment" upperBound="-1"
        eType="ecore:EClass ../../epimodel/model/epimodel.ecore#//CompartmentWrapper"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
