<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="couplingFlow" nsURI="http://www.example.org/couplingFlow" nsPrefix="couplingFlow">
  <eClassifiers xsi:type="ecore:EClass" name="CouplingFlow" eSuperTypes="../../epimodel/model/epimodel.ecore#//Flow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="firstFrom" eType="ecore:EClass ../../epimodel/model/epimodel.ecore#//CompartmentWrapper"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="secondFrom" eType="ecore:EClass ../../epimodel/model/epimodel.ecore#//CompartmentWrapper"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="secondTo" eType="ecore:EClass ../../epimodel/model/epimodel.ecore#//CompartmentWrapper"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="firstTo" eType="ecore:EClass ../../epimodel/model/epimodel.ecore#//CompartmentWrapper"/>
  </eClassifiers>
</ecore:EPackage>
