<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="compartmentFlowEpidemic" nsURI="http://www.example.org/compartmentFlowEpidemic"
    nsPrefix="compartmentFlowEpidemic">
  <eClassifiers xsi:type="ecore:EClass" name="CompartmentFlowEpidemic" eSuperTypes="../../epimodel/model/epimodel.ecore#//Epidemic">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compartment" upperBound="-1"
        eType="ecore:EClass ../../epimodel/model/epimodel.ecore#//CompartmentWrapper"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flow" upperBound="-1" eType="ecore:EClass ../../epimodel/model/epimodel.ecore#//FlowWrapper"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
