<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dimensionReference" nsURI="http://www.example.org/dimensionReference"
    nsPrefix="dimensionReference">
  <eClassifiers xsi:type="ecore:EClass" name="DimensionLink" eSuperTypes="../../EpidemicDimension/model/epidemicDimension.ecore#//Dimension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimension" eType="ecore:EClass ../../EpidemicDimension/model/epidemicDimension.ecore#//Dimension"/>
  </eClassifiers>
</ecore:EPackage>
