/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getPhysicalEpidemicAccess().getGroup(), "rule__PhysicalEpidemic__Group__0");
			builder.put(grammarAccess.getPhysicalEpidemicAccess().getGroup_3(), "rule__PhysicalEpidemic__Group_3__0");
			builder.put(grammarAccess.getPhysicalEpidemicAccess().getGroup_3_3(), "rule__PhysicalEpidemic__Group_3_3__0");
			builder.put(grammarAccess.getPhysicalEpidemicAccess().getGroup_4(), "rule__PhysicalEpidemic__Group_4__0");
			builder.put(grammarAccess.getPhysicalEpidemicAccess().getGroup_4_3(), "rule__PhysicalEpidemic__Group_4_3__0");
			builder.put(grammarAccess.getPhysicalCompartmentAccess().getGroup(), "rule__PhysicalCompartment__Group__0");
			builder.put(grammarAccess.getPhysicalCompartmentAccess().getGroup_3(), "rule__PhysicalCompartment__Group_3__0");
			builder.put(grammarAccess.getPhysicalCompartmentAccess().getGroup_3_3(), "rule__PhysicalCompartment__Group_3_3__0");
			builder.put(grammarAccess.getPhysicalFlowAccess().getGroup(), "rule__PhysicalFlow__Group__0");
			builder.put(grammarAccess.getPhysicalFlowAccess().getGroup_2(), "rule__PhysicalFlow__Group_2__0");
			builder.put(grammarAccess.getPhysicalFlowAccess().getGroup_3(), "rule__PhysicalFlow__Group_3__0");
			builder.put(grammarAccess.getPhysicalFlowAccess().getGroup_4(), "rule__PhysicalFlow__Group_4__0");
			builder.put(grammarAccess.getLabelAccess().getGroup(), "rule__Label__Group__0");
			builder.put(grammarAccess.getEquationTemplateAccess().getGroup(), "rule__EquationTemplate__Group__0");
			builder.put(grammarAccess.getEquationTemplateAccess().getGroup_3(), "rule__EquationTemplate__Group_3__0");
			builder.put(grammarAccess.getEquationTemplateAccess().getGroup_4(), "rule__EquationTemplate__Group_4__0");
			builder.put(grammarAccess.getEquationTemplateAccess().getGroup_5(), "rule__EquationTemplate__Group_5__0");
			builder.put(grammarAccess.getPhysicalEpidemicAccess().getCompartmentsAssignment_3_2(), "rule__PhysicalEpidemic__CompartmentsAssignment_3_2");
			builder.put(grammarAccess.getPhysicalEpidemicAccess().getCompartmentsAssignment_3_3_1(), "rule__PhysicalEpidemic__CompartmentsAssignment_3_3_1");
			builder.put(grammarAccess.getPhysicalEpidemicAccess().getFlowsAssignment_4_2(), "rule__PhysicalEpidemic__FlowsAssignment_4_2");
			builder.put(grammarAccess.getPhysicalEpidemicAccess().getFlowsAssignment_4_3_1(), "rule__PhysicalEpidemic__FlowsAssignment_4_3_1");
			builder.put(grammarAccess.getPhysicalCompartmentAccess().getLabelsAssignment_3_2(), "rule__PhysicalCompartment__LabelsAssignment_3_2");
			builder.put(grammarAccess.getPhysicalCompartmentAccess().getLabelsAssignment_3_3_1(), "rule__PhysicalCompartment__LabelsAssignment_3_3_1");
			builder.put(grammarAccess.getPhysicalFlowAccess().getIdAssignment_2_1(), "rule__PhysicalFlow__IdAssignment_2_1");
			builder.put(grammarAccess.getPhysicalFlowAccess().getFromAssignment_3_1(), "rule__PhysicalFlow__FromAssignment_3_1");
			builder.put(grammarAccess.getPhysicalFlowAccess().getToAssignment_4_1(), "rule__PhysicalFlow__ToAssignment_4_1");
			builder.put(grammarAccess.getPhysicalFlowAccess().getEquationtemplateAssignment_6(), "rule__PhysicalFlow__EquationtemplateAssignment_6");
			builder.put(grammarAccess.getLabelAccess().getNameAssignment_2(), "rule__Label__NameAssignment_2");
			builder.put(grammarAccess.getEquationTemplateAccess().getSourceParametersAssignment_3_1(), "rule__EquationTemplate__SourceParametersAssignment_3_1");
			builder.put(grammarAccess.getEquationTemplateAccess().getContactParametersAssignment_4_1(), "rule__EquationTemplate__ContactParametersAssignment_4_1");
			builder.put(grammarAccess.getEquationTemplateAccess().getContactCompartmentAssignment_5_1(), "rule__EquationTemplate__ContactCompartmentAssignment_5_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
