/**
 *
 * $Id$
 */
package EpidemicRoot.validation;

import EpidemicRoot.AbstractCompartment;

/**
 * A sample validator interface for {@link EpidemicRoot.Contact}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ContactValidator {
	boolean validate();

	boolean validateContact(AbstractCompartment value);
	boolean validateContactParameters(String value);
}
