<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="epimodel" nsURI="http://www.example.org/epimodel" nsPrefix="epimodel">
  <eClassifiers xsi:type="ecore:EClass" name="Epidemic">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimension" upperBound="-1"
        eType="#//Dimension" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dimension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compartment" upperBound="-1"
        eType="#//MetaCompartment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flow" upperBound="-1" eType="#//MetaFlow"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetaCompartment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetaFlow" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//MetaCompartment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//MetaCompartment"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetaContact" eSuperTypes="#//MetaFlow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contact" eType="#//MetaCompartment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetaRate" eSuperTypes="#//MetaFlow"/>
  <eClassifiers xsi:type="ecore:EClass" name="MetaBatch" eSuperTypes="#//MetaFlow"/>
</ecore:EPackage>
