/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import equationGenerator.ui.internal.EquationGeneratorActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(EquationGeneratorActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		EquationGeneratorActivator activator = EquationGeneratorActivator.getInstance();
		return activator != null ? activator.getInjector(EquationGeneratorActivator.ORG_XTEXT_EXAMPLE_MYDSL_MYDSL) : null;
	}

}
