<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="epidemicDimension" nsURI="http://www.example.org/epidemicDimension"
    nsPrefix="epidemicDimension">
  <eClassifiers xsi:type="ecore:EClass" name="Dimension" eSuperTypes="../../epimodel/model/epimodel.ecore#//Compartment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compartment" upperBound="-1"
        eType="ecore:EClass ../../epimodel/model/epimodel.ecore#//Compartment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flow" upperBound="-1" eType="ecore:EClass ../../epimodel/model/epimodel.ecore#//Flow"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
