<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="epimodel" nsURI="http://www.example.org/epimodel" nsPrefix="epimodel">
  <eClassifiers xsi:type="ecore:EClass" name="CompartmentWrapper">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compartment" lowerBound="1"
        eType="#//Compartment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Compartment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowWrapper">
    <eStructuralFeatures xsi:type="ecore:EReference" name="flow" lowerBound="1" eType="#//Flow"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Flow" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Epidemic">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compartmentwrapper" lowerBound="1"
        eType="#//CompartmentWrapper" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
