package seirmodel.compare;

public enum DifferenceType {
    MODEL_ATTRIBUTE_CHANGED,

    COMPARTMENT_ADDED,
    COMPARTMENT_REMOVED,

    FLOW_ADDED,
    FLOW_REMOVED,

    RATE_CHANGED,          
    CONTACT_RATE_CHANGED, 
    CONTACT_COMPARTMENT_CHANGED, 

    BIRTHSOURCE_ADDED,
    BIRTHSOURCE_REMOVED,
    BIRTH_RATE_CHANGED,

    DEATHSINK_ADDED,
    DEATHSINK_REMOVED,
    DEATH_RATE_CHANGED,

    GROUP_ADDED,
    GROUP_REMOVED,

    PRODUCT_ADDED,
    PRODUCT_REMOVED
}
