<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="EpidemicRoot" nsURI="geodes.sms.mde" nsPrefix="ep">
  <eClassifiers xsi:type="ecore:EClass" name="Epidemic">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compartment" lowerBound="1"
        eType="#//AbstractCompartment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Group" eSuperTypes="#//AbstractCompartment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="flows" upperBound="-1"
        eType="#//Flow" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compartments" upperBound="-1"
        eType="#//AbstractCompartment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sink" upperBound="-1" eType="#//AbstractCompartment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" upperBound="-1"
        eType="#//AbstractCompartment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitCompartment" eSuperTypes="#//AbstractCompartment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Flow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//AbstractCompartment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//AbstractCompartment"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceParameters" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contact" eSuperTypes="#//Flow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contact" eType="#//AbstractCompartment"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contactParameters" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Batch" eSuperTypes="#//Flow"/>
  <eClassifiers xsi:type="ecore:EClass" name="Rate" eSuperTypes="#//Flow"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractCompartment" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product" eSuperTypes="#//AbstractCompartment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compartments" upperBound="-1"
        eType="#//AbstractCompartment" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
