"""
Task 10.2: Create comprehensive report for the model.

Generate a final markdown report summarizing distributions, Monte Carlo
results, sensitivity, and links to plots.
"""

import json
from pathlib import Path
from typing import Any, Dict, List, Optional


def generate_report(
    disease: str,
    report_dir: Path,
    distributions_data: Dict[str, Any],
    monte_carlo_data: Optional[Dict[str, Any]] = None,
    sensitivity_data: Optional[Dict[str, Any]] = None,
    has_uncertainty_plot: bool = False,
    has_sensitivity_plot: bool = False,
) -> str:
    """
    Write PHASE4_REPORT.md for the disease.
    """
    lines = [
        f"# Phase 4 — Uncertainty quantification: {disease.replace('_', ' ').title()}",
        "",
        "This report summarizes parameter distributions (general framework), Monte Carlo simulation, and sensitivity analysis.",
        "",
        "## 1. Parameter distributions (Task 9.1)",
        "",
        "Distributions are assigned using the **general framework** (typed parameter uncertainty): same distribution families and typical ranges for similar parameter types across diseases.",
        "",
    ]
    dists = distributions_data.get("parameter_distributions", {})
    lines.append("| Parameter | Type | Family | Low | High | Point |")
    lines.append("|-----------|------|--------|-----|------|-------|")
    for name, spec in list(dists.items())[:25]:
        ptype = spec.get("parameter_type", "—")
        family = spec.get("family", "—")
        low = spec.get("low", "—")
        high = spec.get("high", "—")
        point = spec.get("point_estimate", "—")
        if low is not None and high is not None and point is None:
            point = (low + high) / 2
        lines.append(f"| {name} | {ptype} | {family} | {low} | {high} | {point} |")
    if len(dists) > 25:
        lines.append(f"| … | … | … | … | … | … (*{len(dists)} total*) |")
    lines.extend(["", "## 2. Monte Carlo simulation (Task 9.2)", ""])

    if monte_carlo_data and "error" not in monte_carlo_data:
        n = monte_carlo_data.get("n_samples", 0)
        lines.append(f"- **Samples:** {n}")
        lines.append(f"- **Days:** {monte_carlo_data.get('days', '—')}")
        lines.append("")
        if has_uncertainty_plot:
            lines.append("- **Uncertainty bands:** see `uncertainty_bands.png`")
            lines.append("")
    else:
        lines.append("- Monte Carlo not run or failed (check Phase 1 simulator and numpy).")
        lines.append("")

    lines.extend(["## 3. Sensitivity analysis (Task 9.3)", ""])
    if sensitivity_data and "error" not in sensitivity_data:
        most = sensitivity_data.get("most_influential", [])
        lines.append("**Most influential parameters:**")
        for p in most:
            lines.append(f"- {p}")
        lines.append("")
        if has_sensitivity_plot:
            lines.append("- **Tornado plot:** see `sensitivity_tornado.png`")
            lines.append("")
    else:
        lines.append("Sensitivity analysis not run or failed.")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by Phase 4 (uncertainty quantification). General framework: `phase 4/data/general_framework.json`.*")

    out_path = report_dir / "PHASE4_REPORT.md"
    report_dir.mkdir(parents=True, exist_ok=True)
    content = "\n".join(lines)
    out_path.write_text(content, encoding="utf-8")
    return content
