#

pluginName = SEIRModel Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_Compartment_type = Compartment
_UI_Flow_type = Flow
_UI_Susceptible_type = Susceptible
_UI_Exposed_type = Exposed
_UI_ExposedNonIsolated_type = Exposed Non Isolated
_UI_InfectiousSymptomatic_type = Infectious Symptomatic
_UI_InfectiousAsymptomatic_type = Infectious Asymptomatic
_UI_Recovered_type = Recovered
_UI_ExposedIsolated_type = Exposed Isolated
_UI_Infectious_type = Infectious
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Compartment_name_feature = Name
_UI_Compartment_population_feature = Population
_UI_Flow_rate_feature = Rate
_UI_Flow_description_feature = Description
_UI_Flow_target_feature = Target
_UI_Susceptible_outgoingFlows_feature = Outgoing Flows
_UI_Exposed_outgoingFlows_feature = Outgoing Flows
_UI_Infectious_outgoingFlows_feature = Outgoing Flows
_UI_Unknown_feature = Unspecified

_UI_SEIRModel_type = SEIR Model
_UI_SEIRModel_compartments_feature = Compartments
_UI_Compartment_outgoingFlows_feature = Outgoing Flows
_UI_Symptomatic_type = Symptomatic
_UI_Asymptomatic_type = Asymptomatic
_UI_Preclinical_type = Preclinical
_UI_Mild_type = Mild
_UI_Severe_type = Severe
_UI_Hospitalized_type = Hospitalized
_UI_Deaths_type = Deaths
_UI_Test_type = Test
_UI_Deceased_type = Deceased
_UI_Infectiouse_Moderate_Symptoms_type = Infectiouse Moderate Symptoms
_UI_Vaccinated_type = Vaccinated
_UI_Sever_Symptomatic_type = Sever Symptomatic
_UI_InfectiousIsolated_type = Infectious Isolated
_UI_InfectiousNonIsolated_type = Infectious Non Isolated
_UI_Hospital_No_Access_type = Hospital No Access
_UI_Compartment_PrimaryName_feature = Primary Name
_UI_Compartment_SecondaryName_feature = Secondary Name
_UI_BirthSource_type = Birth Source
_UI_DeathSink_type = Death Sink
_UI_BirthSource_name_feature = Name
_UI_BirthSource_rate_feature = Rate
_UI_BirthSource_targetCompartment_feature = Target Compartment
_UI_DeathSink_name_feature = Name
_UI_DeathSink_rate_feature = Rate
_UI_DeathSink_sourceCompartment_feature = Source Compartment
_UI_DeathSink_isCOVIDDeath_feature = Is COVID Death
_UI_SEIRModel_birthSources_feature = Birth Sources
_UI_SEIRModel_deathSinks_feature = Death Sinks
_UI_SEIRModel_totalPopulation_feature = Total Population
_UI_SEIRModel_globalBirthRate_feature = Global Birth Rate
_UI_SEIRModel_globalDeathRate_feature = Global Death Rate
_UI_RateFlow_type = Rate Flow
_UI_ContactFlow_type = Contact Flow
_UI_RateFlow_rate_feature = Rate
_UI_ContactFlow_contactCompartment_feature = Contact Compartment
_UI_ContactFlow_contactRate_feature = Contact Rate
_UI_ContactFlow_contactParameters_feature = Contact Parameters
_UI_Group_type = Group
_UI_Product_type = Product
_UI_Compartment_product_feature = Product
_UI_Group_name_feature = Name
_UI_Group_description_feature = Description
_UI_Group_values_feature = Values
_UI_Product_name_feature = Name
_UI_Product_description_feature = Description
_UI_Product_groups_feature = Groups
_UI_SEIRModel_groups_feature = Groups
_UI_SEIRModel_products_feature = Products
_UI_StratumSpecificRate_type = Stratum Specific Rate
_UI_RateFlow_stratumSpecificRates_feature = Stratum Specific Rates
_UI_ContactFlow_stratumSpecificRates_feature = Stratum Specific Rates
_UI_StratumSpecificRate_stratum_feature = Stratum
_UI_StratumSpecificRate_rate_feature = Rate
_UI_StratumSpecificRate_multiplier_feature = Multiplier
_UI_BirthSource_targetStratum_feature = Target Stratum
_UI_BirthSource_fixedRate_feature = Fixed Rate
_UI_DeathSink_sourceStratum_feature = Source Stratum
