/**
 */
package seirmodel.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import seirmodel.util.SeirmodelAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class SeirmodelItemProviderAdapterFactory extends SeirmodelAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public SeirmodelItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link seirmodel.Flow} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FlowItemProvider flowItemProvider;

	/**
	 * This creates an adapter for a {@link seirmodel.Flow}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFlowAdapter() {
		if (flowItemProvider == null) {
			flowItemProvider = new FlowItemProvider(this);
		}

		return flowItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link seirmodel.Susceptible} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SusceptibleItemProvider susceptibleItemProvider;

	/**
	 * This creates an adapter for a {@link seirmodel.Susceptible}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSusceptibleAdapter() {
		if (susceptibleItemProvider == null) {
			susceptibleItemProvider = new SusceptibleItemProvider(this);
		}

		return susceptibleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link seirmodel.ExposedNonIsolated} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExposedNonIsolatedItemProvider exposedNonIsolatedItemProvider;

	/**
	 * This creates an adapter for a {@link seirmodel.ExposedNonIsolated}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExposedNonIsolatedAdapter() {
		if (exposedNonIsolatedItemProvider == null) {
			exposedNonIsolatedItemProvider = new ExposedNonIsolatedItemProvider(this);
		}

		return exposedNonIsolatedItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link seirmodel.Symptomatic} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SymptomaticItemProvider symptomaticItemProvider;

	/**
	 * This creates an adapter for a {@link seirmodel.Symptomatic}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSymptomaticAdapter() {
		if (symptomaticItemProvider == null) {
			symptomaticItemProvider = new SymptomaticItemProvider(this);
		}

		return symptomaticItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link seirmodel.Asymptomatic} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AsymptomaticItemProvider asymptomaticItemProvider;

	/**
	 * This creates an adapter for a {@link seirmodel.Asymptomatic}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAsymptomaticAdapter() {
		if (asymptomaticItemProvider == null) {
			asymptomaticItemProvider = new AsymptomaticItemProvider(this);
		}

		return asymptomaticItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link seirmodel.Recovered} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RecoveredItemProvider recoveredItemProvider;

	/**
	 * This creates an adapter for a {@link seirmodel.Recovered}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRecoveredAdapter() {
		if (recoveredItemProvider == null) {
			recoveredItemProvider = new RecoveredItemProvider(this);
		}

		return recoveredItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link seirmodel.ExposedIsolated} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExposedIsolatedItemProvider exposedIsolatedItemProvider;

	/**
	 * This creates an adapter for a {@link seirmodel.ExposedIsolated}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExposedIsolatedAdapter() {
		if (exposedIsolatedItemProvider == null) {
			exposedIsolatedItemProvider = new ExposedIsolatedItemProvider(this);
		}

		return exposedIsolatedItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link seirmodel.SEIRModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SEIRModelItemProvider seirModelItemProvider;

	/**
	 * This creates an adapter for a {@link seirmodel.SEIRModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSEIRModelAdapter() {
		if (seirModelItemProvider == null) {
			seirModelItemProvider = new SEIRModelItemProvider(this);
		}

		return seirModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link seirmodel.Preclinical} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PreclinicalItemProvider preclinicalItemProvider;

	/**
	 * This creates an adapter for a {@link seirmodel.Preclinical}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPreclinicalAdapter() {
		if (preclinicalItemProvider == null) {
			preclinicalItemProvider = new PreclinicalItemProvider(this);
		}

		return preclinicalItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link seirmodel.Mild} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MildItemProvider mildItemProvider;

	/**
	 * This creates an adapter for a {@link seirmodel.Mild}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMildAdapter() {
		if (mildItemProvider == null) {
			mildItemProvider = new MildItemProvider(this);
		}

		return mildItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link seirmodel.Severe} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SevereItemProvider severeItemProvider;

	/**
	 * This creates an adapter for a {@link seirmodel.Severe}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSevereAdapter() {
		if (severeItemProvider == null) {
			severeItemProvider = new SevereItemProvider(this);
		}

		return severeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link seirmodel.Hospitalized} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HospitalizedItemProvider hospitalizedItemProvider;

	/**
	 * This creates an adapter for a {@link seirmodel.Hospitalized}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHospitalizedAdapter() {
		if (hospitalizedItemProvider == null) {
			hospitalizedItemProvider = new HospitalizedItemProvider(this);
		}

		return hospitalizedItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link seirmodel.Deaths} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeathsItemProvider deathsItemProvider;

	/**
	 * This creates an adapter for a {@link seirmodel.Deaths}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeathsAdapter() {
		if (deathsItemProvider == null) {
			deathsItemProvider = new DeathsItemProvider(this);
		}

		return deathsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link seirmodel.Test} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TestItemProvider testItemProvider;

	/**
	 * This creates an adapter for a {@link seirmodel.Test}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTestAdapter() {
		if (testItemProvider == null) {
			testItemProvider = new TestItemProvider(this);
		}

		return testItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (flowItemProvider != null) flowItemProvider.dispose();
		if (susceptibleItemProvider != null) susceptibleItemProvider.dispose();
		if (exposedNonIsolatedItemProvider != null) exposedNonIsolatedItemProvider.dispose();
		if (symptomaticItemProvider != null) symptomaticItemProvider.dispose();
		if (asymptomaticItemProvider != null) asymptomaticItemProvider.dispose();
		if (recoveredItemProvider != null) recoveredItemProvider.dispose();
		if (exposedIsolatedItemProvider != null) exposedIsolatedItemProvider.dispose();
		if (seirModelItemProvider != null) seirModelItemProvider.dispose();
		if (preclinicalItemProvider != null) preclinicalItemProvider.dispose();
		if (mildItemProvider != null) mildItemProvider.dispose();
		if (severeItemProvider != null) severeItemProvider.dispose();
		if (hospitalizedItemProvider != null) hospitalizedItemProvider.dispose();
		if (deathsItemProvider != null) deathsItemProvider.dispose();
		if (testItemProvider != null) testItemProvider.dispose();
	}

}
